const { REDIS_URL, CLIENT_ID, CLIENT_SECRET, GRANT_TYPE, AUDIENCE, BASE_URL, QUIDAX_SECRET_KEY, WEBHOOKKEY, DB_USERNAME, DB_PASSWORD, DB_NAME, DB_HOST, DB_DIALECT } = process.env

console.log(process.env.REDIS_URL)

module.exports = {
    REDIS_URL,
    CLIENT_ID,
    CLIENT_SECRET,
    GRANT_TYPE,
    AUDIENCE,
    QUIDAX_SECRET_KEY,
    BASE_URL,
    DB_USERNAME,
    DB_PASSWORD,
    DB_NAME,
    DB_HOST,
    DB_DIALECT,
    WEBHOOKKEY
}  